# Generated by Django 5.0.7 on 2024-08-09 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresas',
            old_name='data_final_captacao',
            new_name='data_final',
        ),
    ]
