# Generated by Django 5.0.7 on 2024-08-09 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresarios', '0002_rename_data_final_captacao_empresas_data_final'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresas',
            old_name='data_final',
            new_name='data_final_captacao',
        ),
    ]
